// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_game_board_size_1024 from "./routes/api/game/board/size/1024.ts";
import * as $api_game_board_size_16 from "./routes/api/game/board/size/16.ts";
import * as $api_game_board_size_256 from "./routes/api/game/board/size/256.ts";
import * as $api_game_board_size_4 from "./routes/api/game/board/size/4.ts";
import * as $api_game_board_size_size_ from "./routes/api/game/board/size/[size].ts";
import * as $api_game_board_size_old_api from "./routes/api/game/board/size/old_api.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $GameBoard from "./islands/GameBoard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/game/board/size/1024.ts": $api_game_board_size_1024,
    "./routes/api/game/board/size/16.ts": $api_game_board_size_16,
    "./routes/api/game/board/size/256.ts": $api_game_board_size_256,
    "./routes/api/game/board/size/4.ts": $api_game_board_size_4,
    "./routes/api/game/board/size/[size].ts": $api_game_board_size_size_,
    "./routes/api/game/board/size/old_api.ts": $api_game_board_size_old_api,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/GameBoard.tsx": $GameBoard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
