// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_avatar_address_ from "./routes/api/avatar/[address].ts";
import * as $api_game from "./routes/api/game.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $GameBoard from "./islands/GameBoard.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/avatar/[address].ts": $api_avatar_address_,
    "./routes/api/game.ts": $api_game,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/GameBoard.tsx": $GameBoard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
